base:
  random_state: 42
  project_name: "Credit_Risk_Scoring"

data:
  raw_bank: "data/raw/case_study1.xlsx"
  raw_cibil: "data/raw/case_study2.xlsx"
  interim: "data/interim/merged_data.csv"
  x_train: "data/processed/X_train.csv"
  y_train: "data/processed/y_train.csv"
  x_test: "data/processed/X_test.csv"
  y_test: "data/processed/y_test.csv"

clean:
  missing_value: -99999
  null_threshold: 10000

preprocess:
  preprocess_data: data/interim/merged_data.csv
  test_size: 0.2

mlflow:
  experiment_name: "Credit_Risk_Experiment"
  run_name: "XGBoost_Run_v1"

train:
  model_type: xgboost
  model_path: "models/model.joblib"
  columns_path: "models/model_columns.joblib" 
  label_encoder_path: "models/label_encoder.joblib"

evaluate:
  metrics_file: "metrics.json"

pipeline_config:
  base_dir: "src/credit_risk_model"
  steps:
    - "clean_data.py"
    - "preprocess.py"
    - "train.py"
    - "evaluate.py"

xgboost:
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 6
  num_class: 4

random_forest:
  n_estimators: 200
